language: generic
sudo: required
services:
  - docker

before_install: # before we start to run our test what to do
  #- docker-compose -t vivekkrai/docker-react -f Dockerfile.dev up --build 
  - docker build -t vivekkrai/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true vivekkrai/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-west-1-525463595872"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY